<h3>Add new news</h3>

Fill below files and submit to add new news.
<form name="news_frm_add" action="" method="post">
    <table>
        <tr>
            <td>Name</td>
            <td><input name="news_name" /></td>
        </tr>
        <tr>
            <td>Content</td>
            <td>
                <textarea name="news_content"></textarea>
            </td>
        </tr>
        <tr>
            <td><input type="submit" value="ADD" /></td>
            <td><input type="reset" value="RESET" /></td>
        </tr>
    </table>
</form>